"""
Alert event model.

AlertEvent is the internal representation that flows through the pipeline:
  atlas_publishers → AlertBus → AlertWorker → AlertRouter → TelegramSink → DB

correlation_id semantics: optional UUID of the ATLAS/trade/decision event that
originated this alert (for traceability back to agent messages and validation
rows). NOT a random ID generated by the worker — left None for system alerts
not tied to a specific trade cycle.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    WARN = "WARN"
    INFO = "INFO"


class AlertEventType(str, Enum):
    MARGIN_BREACH = "position.margin_breach"
    STOP_LOSS_HIT = "position.stop_loss_hit"
    SYSTEM_FAILURE = "system.failure"
    ROLL_OPPORTUNITY = "position.roll_opportunity"
    MODE_CHANGED = "system.mode_changed"


class AlertEvent(BaseModel):
    event_type: AlertEventType
    severity: AlertSeverity
    title: str = Field(..., max_length=256)
    payload: dict[str, Any] = Field(default_factory=dict)
    source: str = Field(default="atlas", max_length=64)
    # ID of the originating ATLAS/trade/decision event — None for system alerts.
    correlation_id: UUID | None = None
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
