/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Paginated alert history. Filter by severity and/or event_type.
         */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fire Test Alert
         * @description Publish a test alert to the alert pipeline.
         *     Only available when ENVIRONMENT=development.
         *     Returns 404 in any other environment.
         */
        post: operations["fire_test_alert_alerts_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Current risk mode and portfolio summary. Uses cached snapshot (TTL 5s).
         */
        get: operations["health_atlas_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Run ATLAS risk checks on a proposed trade.
         *
         *     Always returns HTTP 200. approved=False means ATLAS blocked the trade —
         *     this is a valid response, not an error. HTTP 422 signals invalid input only.
         *
         *     Builds synthetic ProposalMessage and DecisionMessage internally.
         *     asset_class=OPTION (default) activates all checks including vega.
         *     Override to EQUITY/CRYPTO to skip vega for non-option strategies.
         */
        post: operations["validate_atlas_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Limits View
         * @description Current Phase 1 risk limits (from config/limits.yaml, lru_cached).
         */
        get: operations["limits_view_atlas_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buckets View
         * @description Ticker→bucket mapping (from config/buckets.yaml, lru_cached).
         */
        get: operations["buckets_view_atlas_buckets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot
         * @description Current portfolio snapshot (cached, TTL 5s).
         */
        get: operations["snapshot_portfolio_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Positions
         * @description All positions from the current cached snapshot.
         */
        get: operations["positions_portfolio_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Validations
         * @description Recent ATLAS validations. Filter by approved status, lookback window, and limit.
         */
        get: operations["list_validations_trades_validations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/validations/{correlation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Validation
         * @description Single validation detail by correlation_id. Returns 404 if not found.
         */
        get: operations["get_validation_trades_validations__correlation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/costs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost Summary
         * @description Aggregate LLM cost stats for the given lookback period.
         */
        get: operations["cost_summary_costs_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/costs/by-agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost By Agent
         * @description LLM costs grouped by agent_id for the given lookback period.
         */
        get: operations["cost_by_agent_costs_by_agent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/costs/by-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost By Task
         * @description LLM costs grouped by task_type for the given lookback period.
         */
        get: operations["cost_by_task_costs_by_task_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/costs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost Daily
         * @description Daily LLM cost totals for the given lookback period.
         */
        get: operations["cost_daily_costs_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health overview
         * @description Returns health of all subsystems. Always responds 200 — individual
         *     subsystems may report 'error' but the endpoint itself does not fail.
         */
        get: operations["status_view_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trading mode and uptime
         * @description Returns current trading mode (paper/real) and backend startup time.
         */
        get: operations["mode_view_system_mode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetClass
         * @enum {string}
         */
        AssetClass: "equity" | "option" | "future" | "crypto" | "etf";
        /** BucketDetail */
        BucketDetail: {
            /** Description */
            description: string;
            /** Tickers */
            tickers: string[];
        };
        /** BucketsResponse */
        BucketsResponse: {
            /** Buckets */
            buckets: {
                [key: string]: components["schemas"]["BucketDetail"];
            };
        };
        /** BuyingPowerLimitsOut */
        BuyingPowerLimitsOut: {
            /** Normal Max Pct */
            normal_max_pct: number;
            /** Macro Event Max Pct */
            macro_event_max_pct: number;
        };
        /** CostByAgentResponse */
        CostByAgentResponse: {
            /** Period Days */
            period_days: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** CostByTaskResponse */
        CostByTaskResponse: {
            /** Period Days */
            period_days: number;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** CostDailyResponse */
        CostDailyResponse: {
            /** Period Days */
            period_days: number;
            /** Rows */
            rows: components["schemas"]["DailyTotalsRow"][];
        };
        /** CostSummaryResponse */
        CostSummaryResponse: {
            /** Period Days */
            period_days: number;
            /** Total Calls */
            total_calls: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Tokens */
            total_tokens: number;
            /** By Model */
            by_model: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DailyTotalsRow
         * @description Single day totals row for /costs/daily endpoint.
         */
        DailyTotalsRow: {
            /**
             * Date
             * @description ISO date (YYYY-MM-DD).
             */
            date: string;
            /**
             * Calls
             * @description Number of LLM calls on this date.
             */
            calls: number;
            /**
             * Cost Usd
             * @description Total cost in USD.
             */
            cost_usd: number;
            /**
             * Total Tokens
             * @description Total tokens (input + output + cache).
             */
            total_tokens: number;
        };
        /** ExposureLimitsOut */
        ExposureLimitsOut: {
            /** Single Name Max Pct */
            single_name_max_pct: number;
            /** Sector Max Pct */
            sector_max_pct: number;
            /** Bucket Max Pct */
            bucket_max_pct: number;
            /** Beta Min */
            beta_min: number;
            /** Beta Max */
            beta_max: number;
        };
        /** GreekLimitsOut */
        GreekLimitsOut: {
            /** Vega Limit Pct Per Vix Point */
            vega_limit_pct_per_vix_point: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Risk Mode */
            risk_mode: string;
            /** Nav Usd */
            nav_usd: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** Ts */
            ts: string;
        };
        /** LimitsResponse */
        LimitsResponse: {
            /** Phase */
            phase: number;
            pnl: components["schemas"]["PnlLimitsOut"];
            exposure: components["schemas"]["ExposureLimitsOut"];
            greeks: components["schemas"]["GreekLimitsOut"];
            buying_power: components["schemas"]["BuyingPowerLimitsOut"];
        };
        /** PnlLimitsOut */
        PnlLimitsOut: {
            /** Daily Halt Pct */
            daily_halt_pct: number;
            /** Weekly Halt Pct */
            weekly_halt_pct: number;
            /** Monthly Size Reduction Pct */
            monthly_size_reduction_pct: number;
            /** Drawdown Halt Pct */
            drawdown_halt_pct: number;
            /** Drawdown Kill Switch Pct */
            drawdown_kill_switch_pct: number;
            /** Daily Loss Kill Switch Pct */
            daily_loss_kill_switch_pct: number;
        };
        /** PositionResponse */
        PositionResponse: {
            /** Ticker */
            ticker: string;
            /** Asset Class */
            asset_class: string;
            /** Strategy Type */
            strategy_type: string | null;
            /** Market Value Usd */
            market_value_usd: number;
            /** Quantity */
            quantity: number;
            /** Delta */
            delta: number;
            /** Vega */
            vega: number;
            /** Theta */
            theta: number;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Nav Usd */
            nav_usd: number;
            /** Cash Usd */
            cash_usd: number;
            /** Buying Power Used Pct */
            buying_power_used_pct: number;
            /** Portfolio Beta */
            portfolio_beta: number;
            /** Vega Total */
            vega_total: number;
            /** Pnl Daily Usd */
            pnl_daily_usd: number;
            /** Pnl Daily Pct */
            pnl_daily_pct: number;
            /** Pnl Weekly Pct */
            pnl_weekly_pct: number;
            /** Pnl Monthly Pct */
            pnl_monthly_pct: number;
            /** Drawdown From Peak Pct */
            drawdown_from_peak_pct: number;
            /** Snapshot At */
            snapshot_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Position Count */
            position_count: number;
        };
        /**
         * StrategyType
         * @enum {string}
         */
        StrategyType: "CSP" | "COVERED_CALL" | "CREDIT_SPREAD" | "DEBIT_SPREAD" | "IRON_CONDOR" | "LEAP" | "CALENDAR" | "SWING_EQUITY" | "CRYPTO_SPOT" | "ZERO_DTE" | "WEEKLY" | "SECTOR_ROTATION";
        /**
         * SystemModeResponse
         * @description Current trading mode and backend startup time.
         */
        SystemModeResponse: {
            /**
             * Mode
             * @description paper or real, controlled by TRADING_MODE env var.
             * @enum {string}
             */
            mode: "paper" | "real";
            /**
             * Since
             * Format: date-time
             * @description When the backend started (UTC).
             */
            since: string;
        };
        /**
         * SystemStatusResponse
         * @description Health overview of all subsystems.
         */
        SystemStatusResponse: {
            /**
             * Api
             * @description API service. Always 'ok' if this endpoint responded.
             * @enum {string}
             */
            api: "ok" | "error" | "unknown";
            /**
             * Bus
             * @description Redis bus (used by alerts pub/sub and message streams).
             * @enum {string}
             */
            bus: "ok" | "error" | "unknown";
            /**
             * Atlas
             * @description ATLAS risk module (buckets and limits loaded).
             * @enum {string}
             */
            atlas: "ok" | "error" | "unknown";
            /**
             * Db
             * @description PostgreSQL connection pool.
             * @enum {string}
             */
            db: "ok" | "error" | "unknown";
            /**
             * Checks Duration Ms
             * @description Duration of each individual health check in milliseconds.
             */
            checks_duration_ms: {
                [key: string]: number;
            };
            /**
             * Checked At
             * Format: date-time
             * @description When the health checks were performed (UTC).
             */
            checked_at: string;
        };
        /**
         * ValidateRequest
         * @description Input for POST /atlas/validate.
         *
         *     asset_class defaults to OPTION (activates all checks including vega).
         *     Override to EQUITY/CRYPTO for non-option strategies to skip vega check.
         */
        ValidateRequest: {
            /** Ticker */
            ticker: string;
            strategy_type: components["schemas"]["StrategyType"];
            /** @default option */
            asset_class: components["schemas"]["AssetClass"];
            /**
             * Proposed Size Pct
             * @description % of portfolio NAV
             */
            proposed_size_pct: number;
            /**
             * Buying Power Required
             * @description USD buying power required
             */
            buying_power_required: number;
            /** Conviction Score */
            conviction_score: number;
        };
        /**
         * ValidateResponse
         * @description Output for POST /atlas/validate. Always 200 — approved=False means ATLAS blocked.
         */
        ValidateResponse: {
            /** Correlation Id */
            correlation_id: string;
            /** Approved */
            approved: boolean;
            /** Executed Size Pct */
            executed_size_pct: number;
            /** Original Size Pct */
            original_size_pct: number;
            /** Reason */
            reason: string;
            /** Risk Mode */
            risk_mode: string;
            /** Checks Passed */
            checks_passed: string[];
            /** Checks Failed */
            checks_failed: string[];
            /** Evaluation Time Ms */
            evaluation_time_ms: number;
            /** Atlas Version */
            atlas_version: string;
            /** Portfolio Snapshot Id */
            portfolio_snapshot_id: string;
            /** Metrics Snapshot */
            metrics_snapshot: {
                [key: string]: unknown;
            };
        };
        /** ValidationDetailResponse */
        ValidationDetailResponse: {
            /** Correlation Id */
            correlation_id: string;
            /** Approved */
            approved: boolean | null;
            /** Executed Size Pct */
            executed_size_pct: number | null;
            /** Original Size Pct */
            original_size_pct: number | null;
            /** Reason */
            reason: string | null;
            /** Atlas Version */
            atlas_version: string | null;
            /** Portfolio Snapshot Id */
            portfolio_snapshot_id: string | null;
            /** Evaluation Time Ms */
            evaluation_time_ms: number | null;
            /** Checks Passed */
            checks_passed: string[] | null;
            /** Checks Failed */
            checks_failed: string[] | null;
            /** Risk Mode */
            risk_mode: string | null;
            /** Created At */
            created_at: string | null;
            /** Metrics Snapshot */
            metrics_snapshot: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationSummaryItem */
        ValidationSummaryItem: {
            /** Correlation Id */
            correlation_id: string;
            /** Approved */
            approved: boolean | null;
            /** Executed Size Pct */
            executed_size_pct: number | null;
            /** Original Size Pct */
            original_size_pct: number | null;
            /** Reason */
            reason: string | null;
            /** Atlas Version */
            atlas_version: string | null;
            /** Portfolio Snapshot Id */
            portfolio_snapshot_id: string | null;
            /** Evaluation Time Ms */
            evaluation_time_ms: number | null;
            /** Checks Passed */
            checks_passed: string[] | null;
            /** Checks Failed */
            checks_failed: string[] | null;
            /** Risk Mode */
            risk_mode: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** ValidationsListResponse */
        ValidationsListResponse: {
            /** Items */
            items: components["schemas"]["ValidationSummaryItem"][];
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                severity?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fire_test_alert_alerts_test_post: {
        parameters: {
            query?: {
                event_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_atlas_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_atlas_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    limits_view_atlas_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsResponse"];
                };
            };
        };
    };
    buckets_view_atlas_buckets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketsResponse"];
                };
            };
        };
    };
    snapshot_portfolio_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    positions_portfolio_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"][];
                };
            };
        };
    };
    list_validations_trades_validations_get: {
        parameters: {
            query?: {
                approved?: boolean | null;
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_trades_validations__correlation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correlation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_summary_costs_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_by_agent_costs_by_agent_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostByAgentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_by_task_costs_by_task_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostByTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_daily_costs_daily_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostDailyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_view_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    mode_view_system_mode_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemModeResponse"];
                };
            };
        };
    };
}
