from __future__ import annotations

from .base import BaseMessage
from .enums import (
    AgentId,
    AssetClass,
    AtlasDecision,
    AtlasReason,
    ConsensusType,
    DecisionOutcome,
    Direction,
    MessageType,
    OptionType,
    RiskMode,
    Stance,
    StrategyType,
    TradeResult,
    TradeSource,
    TradeStatus,
)
from .factory import deserialize_message
from .message_bus import AgentChannels, AgentMessageBus, ConsumerGroups
from .schemas import (
    AtlasValidationMessage,
    CalibrationUpdate,
    ConsensusState,
    CritiqueArgument,
    CritiqueMessage,
    DataSignature,
    DecisionMessage,
    DissentEvaluation,
    EvidenceItem,
    ExecutionMessage,
    FillRecord,
    OptionLeg,
    PostmortemMessage,
    ProposalMessage,
    SizeModulation,
    SlippageInfo,
    Thesis,
    ThesisEvaluation,
    TradeDetails,
    TradeOutcome,
    TradeSizing,
    TradeStructure,
)

__all__ = [
    "BaseMessage",
    "deserialize_message",
    "AgentMessageBus",
    "AgentChannels",
    "ConsumerGroups",
    # Enums
    "MessageType",
    "AgentId",
    "AssetClass",
    "Direction",
    "OptionType",
    "TradeSource",
    "TradeStatus",
    "StrategyType",
    "Stance",
    "DecisionOutcome",
    "ConsensusType",
    "AtlasDecision",
    "AtlasReason",
    "RiskMode",
    "TradeResult",
    # Schemas
    "ProposalMessage",
    "OptionLeg",
    "TradeStructure",
    "TradeDetails",
    "Thesis",
    "TradeSizing",
    "DataSignature",
    "CritiqueMessage",
    "EvidenceItem",
    "CritiqueArgument",
    "DecisionMessage",
    "ConsensusState",
    "SizeModulation",
    "AtlasValidationMessage",
    "ExecutionMessage",
    "FillRecord",
    "SlippageInfo",
    "PostmortemMessage",
    "TradeOutcome",
    "ThesisEvaluation",
    "DissentEvaluation",
    "CalibrationUpdate",
]
